extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:lodash-fp/recommended'
env:
  node: true
  jest: true
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  # https://github.com/babel/eslint-plugin-babel
  - babel
rules:
  no-console: 0
